# Generated by Django 3.1.7 on 2021-02-24 06:10

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', django_editorjs.fields.EditorJsField()),
            ],
        ),
    ]
